# SPDX-License-Identifier: GPL-2.0-only

networks:
  smo:
    external: true

services:
  pm-rapp:
    image: $PMRAPP_IMAGE
    container_name: pm-rapp
    environment:
      APPID: pm-rapp
      APPNS: 'nonrtric'
      KAFKA_SERVER: kafka:9092
      ICS: ics:8083
      TOPIC: pmreports
      LOG_PAYLOAD: '1'
      GZIP: ''
      CREDS_GRANT_TYPE: client_credentials
      CREDS_CLIENT_SECRET: $PMRAPP_CLIENT_SECRET
      CREDS_CLIENT_ID: pm-rapp
    volumes:
    - ./config/pmrapp:/config
    labels:
      - "ranpm=yes"
      - "ranpmrapp=yes"
    networks:
      smo:

