# SPDX-License-Identifier: GPL-2.0-only

networks:
  smo:
    external: true
    name: smo

services:
  auth-token-file-pmlog-0:
    image: $AUTH_TOKEN_IMAGE
    environment:
      CREDS_GRANT_TYPE: client_credentials
      CREDS_CLIENT_SECRET: $PMLOG_CLIENT_SECRET
      CREDS_CLIENT_ID: nrt-pm-log
      AUTH_SERVICE_URL: http://keycloak:8080/realms/nonrtric-realm/protocol/openid-connect/token
      OUTPUT_FILE: /token-cache/jwt.txt
    volumes:
    - ./config/pmlog/token-cache:/token-cache
    labels:
      - "ranpm=yes"
      - "ranpmlog=yes"
    networks:
      smo:

  pmlog-0:
    image: $PMLOG_IMAGE
    container_name: pmlog-0
    depends_on:
      - auth-token-file-pmlog-0
    environment:
      APP_INFLUX_ACCESSTOKEN: $INFLUXDB2_TOKEN
    volumes:
    - ./config/pmlog/jobDefinition.json:/opt/app/pmlog-service/config/jobDefinition.json
    - ./config/pmlog/application.yaml:/opt/app/pmlog-service/config/application.yaml
    - ./config/pmlog/token-cache:/token-cache
    ports:
    - 8184:8084
    - 8436:8436
    labels:
      - "ranpm=yes"
      - "ranpmlog=yes"
    networks:
      smo:
