services:
  ric1:
    image: nexus3.o-ran-sc.org:10002/o-ran-sc/a1-simulator:2.7.0
    container_name: ric1
    hostname: ric1
    networks:
      smo:
    environment:
        ALLOW_HTTP: true
        A1_VERSION: OSC_2.1.0
    ports:
      - 18085:8085
      - 18185:8185
  ric2:
    image: nexus3.o-ran-sc.org:10002/o-ran-sc/a1-simulator:2.7.0
    container_name: ric2
    hostname: ric2
    networks:
      smo:
    environment:
        ALLOW_HTTP: true
        A1_VERSION: STD_1.1.3
    ports:
      - 28085:8085
      - 28185:8185
  ric3:
    image: nexus3.o-ran-sc.org:10002/o-ran-sc/a1-simulator:2.7.0
    container_name: ric3
    hostname: ric3
    networks:
      smo:
    environment:
        ALLOW_HTTP: true
        A1_VERSION: STD_2.0.0
    ports:
      - 38085:8085
      - 38185:8185

networks:
    smo:
      external: true
