name: Submodule dmaapadapter CI

on:
  workflow_dispatch:

env:
  GHCR_REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true

    # Set up Java 
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Download Setting.xml
      run: |
        cd 
        ls -la
        cd .m2
        rm settings.xml
        wget https://git.onap.org/oparent/plain/settings.xml

        
    - name: Build DMAAP-Adapter Docker Images
      run: |
        ls -la
        cd deps/dmaapadapter
        ls -la
        mvn clean install -Dmaven.test.skip=true

    - name: Show The Build Docker Images
      run: |
        docker images

    - name: Login to GitHub Container Registry (ghcr.io) for push
      uses: docker/login-action@v3.1.0
      with:
        registry: ${{ env.GHCR_REGISTRY }}
        username: ${{ secrets.GHCRUSER }}
        password: ${{ secrets.GHCRPASS }}

    - name: Tag & Push Docker Images
      run: |
        docker tag o-ran-sc/nonrtric-plt-dmaapadapter:latest ghcr.io/ios-mcn-smo/nonrtric-plt-dmaapadapter:1.4.0
        docker push ghcr.io/ios-mcn-smo/nonrtric-plt-dmaapadapter:1.4.0
