name: Submodule dmaapmediator CI

on:
  workflow_dispatch:

env:
  GHCR_REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Build DMAAP-Mediator Docker Images
      run: |
        ls -la
        cd deps/dmaapmediator
        ls -la
        docker build -t o-ran-sc/nonrtric-plt-dmaapmediatorproducer:1.2.0 .

    - name: Show The Build Docker Images
      run: |
        docker images

    - name: Login to GitHub Container Registry (ghcr.io) for push
      uses: docker/login-action@v3.1.0
      with:
        registry: ${{ env.GHCR_REGISTRY }}
        username: ${{ secrets.GHCRUSER }}
        password: ${{ secrets.GHCRPASS }}

    - name: Tag & Push Docker Images
      run: |
        docker tag o-ran-sc/nonrtric-plt-dmaapmediatorproducer:1.2.0 ghcr.io/ios-mcn-smo/nonrtric-plt-dmaapmediatorproducer:1.2.0
        docker push ghcr.io/ios-mcn-smo/nonrtric-plt-dmaapadapter:1.2.0
